<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DungeonFortress.Presentation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DungeonFortress.Simulation\DungeonFortress.Simulation.csproj" />
  </ItemGroup>
</Project>
